/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import CustomerPack.Customer;
import CustomerPack.CustomerCollection;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class SearchBestCustomer extends javax.swing.JFrame {
    private final CustomerCollection customerCollection;

    /**
     * Creates new form Mainform
     */
    public SearchBestCustomer(CustomerCollection customerCollection) {
        initComponents();
        setLocationRelativeTo(null);
        this.customerCollection=customerCollection;
        loadBestCustomer();
    }
    
    public void loadBestCustomer(){
        Customer[] customer=customerCollection.toArray();
        Customer[] bestCustomers = new Customer[0];

        for (int i = 0; i < customer.length; i++) {
            if (!customerCollection.searchDuplicateCustomers(bestCustomers, customer[i].getCusId())) {
                Customer[] temp = new Customer[bestCustomers.length + 1];
                for (int j = 0; j < bestCustomers.length; j++) {
                    temp[j] = bestCustomers[j];
                }
                bestCustomers = temp;
                bestCustomers[bestCustomers.length - 1] = 
                        new Customer(customer[i].getOrderId(), 
                                customer[i].getName(), 
                                customer[i].getCusId(), 
                                customer[i].getBgrQty(), 
                                customer[i].getOrderStatus());
            }
        }

        for (int i = 0; i < bestCustomers.length; i++) {
            int bgrQty = 0;
            for (int j = 0; j < customer.length; j++) {
                if (customer[j].getCusId().equalsIgnoreCase(bestCustomers[i].getCusId())) {
                    bgrQty += customer[j].getBgrQty();
                }
            }
            bestCustomers[i].setBgrQty(bgrQty);
        }

        for (int i = 0; i < bestCustomers.length; i++) {
            for (int j = 0; j < bestCustomers.length - 1; j++) {
                if (bestCustomers[j].getBgrQty()< bestCustomers[j + 1].getBgrQty()) {
                    Customer temp = bestCustomers[j];
                    bestCustomers[j] = bestCustomers[j + 1];
                    bestCustomers[j + 1] = temp;
                }
            }
        }

        DefaultTableModel dtm = (DefaultTableModel) tblSBcustomers.getModel();
        dtm.setRowCount(0);
        for (Customer burger : bestCustomers) {
            Object[] rowData = {burger.getCusId(), burger.getName(), burger.getBgrQty()*Customer.bgrPrice};
            dtm.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSback = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSBcustomers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Window");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Best Customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        btnSback.setBackground(new java.awt.Color(255, 0, 51));
        btnSback.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSback.setForeground(new java.awt.Color(255, 255, 255));
        btnSback.setText("Back");
        btnSback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSbackActionPerformed(evt);
            }
        });

        tblSBcustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSBcustomers);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSback, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnSback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSbackActionPerformed
        new MainSearch(customerCollection).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSbackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSBcustomers;
    // End of variables declaration//GEN-END:variables
}
